[profile.default]
src = "src"
out = "out"
libs = ["lib"]

solc = "0.8.18"
auto_detect_solc = false
optimizer = true
optimizer_runs = 10_000_000

[rpc_endpoints]
avax = "https://api.avax.network/ext/bc/C/rpc"
avaxfuji = "https://api.avax-test.network/ext/bc/C/rpc"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config