[profile.default]
src = "src"
out = "out"
libs = ["lib"]

solc = "0.8.18"
auto_detect_solc = false
optimizer = true
optimizer_runs = 10_000_000

# See more config options https://github.com/foundry-rs/foundry/tree/master/config